import numpy as np


def get_target(df, periods=1, sigma_threshold=0.5):
    # --- 1. Calculate Future Return ---
    # Shift backwards to see what happens 'periods' days later
    future_close = df["close"].shift(-periods)

    # Log returns (Additive, symmetric)
    df["log_ret"] = np.log(future_close / df["close"])

    # --- 2. Normalize by Volatility (The "JKX" Paper Trick) ---
    # Calculate daily volatility (trailing 20 days) to avoid look-ahead
    daily_returns = np.log(df["close"] / df["close"].shift(1))
    volatility = daily_returns.rolling(20).std()

    # Calculate "Normalized Return" (Z-Score)
    # Value of 2.0 means price moved 2 standard deviations
    df["norm_ret"] = df["log_ret"] / volatility

    # --- 3. Create Classes (The Hurdle) ---
    # We use the Normalized Return for the hurdle
    # 0 = Sell (Significant Down Move)
    # 1 = Neutral (Noise / Small Move)
    # 2 = Buy (Significant Up Move)

    # Initialize all as Neutral (1)
    df["target"] = 1

    # Buy: If move is > +0.5 sigma
    df.loc[df["norm_ret"] > sigma_threshold, "target"] = 2

    # Sell: If move is < -0.5 sigma
    df.loc[df["norm_ret"] < -sigma_threshold, "target"] = 0

    # Cleanup: Drop NaN values generated by rolling window and shift
    return df.dropna()
